<?php

declare(strict_types=1);

namespace Mammatus\Queue\Consumer;

use Mammatus\DevApp\Queue\EmptyMessage;
use Mammatus\Groups\Attributes\Group;
use Mammatus\Groups\Contracts\LifeCycleHandler;
use Mammatus\Groups\Type;
use Mammatus\Queue\Consumer;
use Psr\Log\LoggerInterface;
use React\Promise\PromiseInterface;
use WyriHaximus\PSR3\ContextLogger\ContextLogger;

/**
 * This class is generated by mammatus/queue, do not edit manually.
 * Or do, I'm not your parent, they will be overwritten next composer install/update ¯\_(ツ)_/¯.
 */
#[Group(Type::Daemon, 'queue-worker-noop-leeg')]
final class MammatusDevAppQueueBarViaRoundForNoopWithMammatusDevAppQueueEmptyMessageAsLeeg implements LifeCycleHandler
{
    private const string QUEUE     = 'noop';
    private const string DTO_CLASS = EmptyMessage::class;

    /** @var ?PromiseInterface<mixed> */
    private PromiseInterface|null $promise = null;

    private readonly LoggerInterface $logger;

    public function __construct(
        private readonly Consumer $consumer,
        LoggerInterface $logger,
    ) {
        $this->logger = new ContextLogger($logger, [
            'queue' => self::QUEUE,
            'dtoClass' => self::DTO_CLASS,
        ]);
    }

    public static function group(): string
    {
        return 'queue-worker-noop-leeg';
    }

    public function start(): void
    {
        $this->logger->debug('Starting consumer for queue {queue} with DTO {dtoClass}');
        $this->promise = $this->consumer->setupConsumer(WorkerFactory\MammatusDevAppQueueBarViaRoundForNoopWithMammatusDevAppQueueEmptyMessageAsLeeg::create());
        $this->logger->debug('Started consumer for queue {queue} with DTO {dtoClass}');
    }

    public function stop(): void
    {
        $this->logger->debug('Stopping consumer for queue {queue} with DTO {dtoClass}');
        $this->promise?->cancel();
        $this->logger->debug('Stopped consumer for queue {queue} with DTO {dtoClass}');
    }
}
