<?php

declare(strict_types=1);

namespace Mammatus\Queue\Consumer;

use Mammatus\Groups\Attributes\Group;
use Mammatus\Groups\Contracts\LifeCycleHandler;
use Mammatus\Groups\Type;
use Mammatus\Queue\Consumer;
use React\Promise\PromiseInterface;

/**
 * This class is generated by mammatus/queue, do not edit manually.
 * Or do, I'm not your parent, they will be overwritten next composer install/update ¯\_(ツ)_/¯.
 */
#[Group(Type::Daemon, 'queue-worker-noop-vol')]
final class MammatusDevAppQueueBarViaRoundForNoopWithMammatusDevAppQueueBeerMessageAsVol implements LifeCycleHandler
{
    /** @var ?PromiseInterface<mixed> */
    private PromiseInterface|null $promise = null;

    public function __construct(
        private readonly Consumer $consumer,
        //        private readonly \Psr\Log\LoggerInterface $logger,
    ) {
    }

    public static function group(): string
    {
        return 'queue-worker-noop-vol';
    }

    public function start(): void
    {
//        $this->logger->debug('Starting consumer: {serverName}', ['serverName' => self::NAME]);
        $this->promise = $this->consumer->setupConsumer(WorkerFactory\MammatusDevAppQueueBarViaRoundForNoopWithMammatusDevAppQueueBeerMessageAsVol::create());
//        $this->logger->debug('Started server: {serverName}', ['serverName' => self::NAME]);
    }

    public function stop(): void
    {
//        $this->logger->debug('Stopping server: {serverName}', ['serverName' => self::NAME]);
        $this->promise?->cancel();
//        $this->logger->debug('Stopped server: {serverName}', ['serverName' => self::NAME]);
    }
}
