on:
  repository_dispatch:
    types:
      - dependency_update # For Packagist Conductor

name: Utils

permissions:
  contents: write

jobs:
  ci:
    name: Continuous Integration
    uses: WyriHaximus/github-workflows/.github/workflows/package-utils.yaml@5343944be2a6ef963186b5f413121fcf36980b33 # v1.0.0
