on:
  repository_dispatch:
    types:
      - dependency_update # For Packagist Conductor

name: Utils

permissions:
  contents: write

jobs:
  ci:
    name: Continuous Integration
    uses: WyriHaximus/github-workflows/.github/workflows/package-utils.yaml@f7d123a11d05722a3d9e6679a2b54be245268ac6 # main
